### ISSUE TITLE
Crust mainnet launch checklist

### ISSUE THREAD

**Issue by yyd106** [crustio/crust#691]
- [x] Technical and economic parameters of Crust mainnet are finalized
- [ ] Mainnet code is complete
  - [ ] [Chain code](https://github.com/crustio/crust/tree/mainnet-staging) is complete
  - [ ] [Chain code](https://github.com/crustio/crust/tree/mainnet-staging) testing is complete
  - [ ] [Storage Worker](https://github.com/crustio/crust-sworker/tree/mainnet-staging) module code is complete
  - [ ] [Storage Worker](https://github.com/crustio/crust-sworker/tree/mainnet-staging) module code testing is complete
- [ ] Auditing for Crust mainnet code is complete
- [ ] [CRU claim](https://github.com/decloudf/crust-bridge) on Crust mainnet is enabled
- [ ] Mainnet [Storage Manager](https://github.com/crustio/crust-smanager) technical test complete
- [ ] The mainnet is open and all nodes are allowed to join
- [ ] DSM (Decentralized Storage Market) test completed
- [ ] DSM (Decentralized Storage Market) features are enabled

**Comment by appoipp** [comment]
Good job
